# for reference, see https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

# MD024/no-duplicate-heading/no-duplicate-header: Multiple headings with the same content
MD024: false
